---
title: "Supplementary Figure 7. Species-specific motifs in the HD family"
output: 
  pdf_document:
    fig_caption: yes
    toc: no
    includes:
      in_header: header.tex
  html_document:
    fig_caption: yes
    self_contained: no
    toc: no
---
```{r setup, include=FALSE, echo=FALSE}
library(knitr)
opts_knit$set(progress=FALSE, verbose=FALSE, keep_md=TRUE)
opts_chunk$set(comment=NA, warning=FALSE, message=FALSE, fig.width=8, fig.pos="!htb")
```
```{r loadLib, message=FALSE, warning=FALSE, error=FALSE, echo=FALSE}
##load the library
library(motifStack)
```
```{r dataInput}
getMatAlignOut <- function(pcmpath, outpath="output", 
                          groupDistance=NA, trim=0.2){
    pcms <- readPCM(pcmpath)
    pfms<-lapply(pcms,pcm2pfm)
    matalign_path <- "./app/matalign-v4a"
    neighbor_path <- "./app/neighbor.app/Contents/MacOS/neighbor"
    system(paste("perl MatAlign2tree.pl --in . --pcmpath", pcmpath, 
                 "--out", outpath,
                 "--matalign", matalign_path, 
                 "--neighbor", neighbor_path, 
                 "--tree","UPGMA"))
    newickstrUPGMA <- 
        readLines(con=file.path(outpath, "NJ.matalign.distMX.nwk"))
    phylog <- newick2phylog(newickstrUPGMA, FALSE)
    leaves <- names(phylog$leaves)
    motifs <- pfms[leaves]
    if(!is.na(groupDistance)){
        motifSig <- 
            motifSignature(motifs, phylog, 
                           groupDistance=groupDistance, 
                           min.freq=1, trim=trim)
        sig <- signatures(motifSig)
        gpCol <- sigColor(motifSig)
    }else{
        motifSig <- NA
        sig <- NA
        gpCol <- NA
    }
    
    return(list(phylog=phylog, sig=sig, gpCol=gpCol, 
                motifs=DNAmotifAlignment(motifs), 
                leaves=leaves, 
                unaligned.pfms=motifs))
}

pcmpath <- dir("pcmsUni", include.dirs=TRUE)[7]
matAlignOut <- lapply(file.path("pcmsUni", pcmpath), 
                      getMatAlignOut, groupDistance=4)
description <- c("Species-specific motifs")
colorSet <- c("Dm"="#00FC00", 
              "Mm"="brown", "Ms"="#F69156", 
              "Hs"="#D900D9")
```

```{r expand, echo=FALSE}
kexpand<-function(.ele, id, cap, figheight, des){
    text <- paste("{{des}}\n\n```{r {{cap}},fig.cap='{{cap}}',fig.height={{figheight}},echo=",
                  ifelse(id==1,"TRUE","FALSE"),
                  "}\n\n
leaveNames <- gsub('^(Dm|Mm|Ms|Hs)_', '', .ele$leaves)\n\n
species <- colorSet[gsub(\"^(Dm|Mm|Ms|Hs).*$\", \"\\\\1\", .ele$leaves)]\n\n
motifPiles(phylog=.ele$phylog, .ele$motifs, 
           .ele$sig, 
           col.tree=species, col.leaves=species, 
           col.pfms2=.ele$gpCol, 
           col.pfms2.width=.01, labels.leaves=leaveNames, 
           plotIndex=c(FALSE,TRUE), IndexCex=1.5, 
           groupDistance=4, clabel.leaves=3)\n\n
```\n\n", sep="")
    cat(knit(text=knit_expand(text=text)))
}
```

```{r plots, results='asis', echo=FALSE}
sta <- mapply(function(.ele, name, ID, des){
    kexpand(.ele, id=ID, cap="__Supplementary Figure 7a__: Species-specific motifs", figheight=ceiling(.25*length(.ele$leaves)), des)
}, matAlignOut, pcmpath, 1:length(pcmpath), description)

```

```{r}
colorSet <- c("Dm"="#00FC00", "b1h"="#00FC00", "sw"="#008080", "bml"="darkgreen", 
              "Mm"="brown", "MmDREAM"="blue", "Ms"="#F69156", 
              "Hs"="#D900D9")

## function to read example data
readDataDoAna <- function(pcmpath, outpath="output", groupDistance=2.5, trim=0.2){
    pcms <- readPCM(pcmpath)
    pfms<-lapply(pcms,pcm2pfm)
    matalign_path <- "./app/matalign-v4a"
    neighbor_path <- "./app/neighbor.app/Contents/MacOS/neighbor"
    system(paste("perl MatAlign2tree.pl --in . --pcmpath", pcmpath, "--out", outpath,
             "--matalign", matalign_path, "--neighbor", neighbor_path, "--tree","UPGMA"))
    newickstrUPGMA <- readLines(con=file.path(outpath, "NJ.matalign.distMX.nwk"))
    phylog <- newick2phylog(newickstrUPGMA, FALSE)
    phylog <- reorderUPGMAtree(phylog, pfms)
    leaves <- names(phylog$leaves)
    motifs <- pfms[leaves]
    if(!is.na(groupDistance)){
        motifSig <- motifSignature(motifs, phylog, groupDistance=groupDistance, 
                                   min.freq=1, trim=trim)
        sig <- signatures(motifSig)
        gpCol <- sigColor(motifSig)
    }else{
        motifSig <- NA
        sig <- NA
        gpCol <- NA
    }
    
    return(list(phylog=phylog, sig=sig, gpCol=gpCol, 
                motifs=DNAmotifAlignment(motifs, minimalConsensus=3), 
                leaves=leaves, unaligned.pfms=motifs))
}

```

```{r Fly_DNA, fig.width=6, fig.height=6, dpi=150, fig.cap="__Supplementary Figure 7b__: Species-specific motifs in the HD family plotted together with common motif clusters", echo=FALSE}
gpDis <- 2
Fly_DNA <- readDataDoAna("pcmsDatasetFly", groupDistance=gpDis)
unUnique <- Fly_DNA$sig

pcms <- readPCM(file.path("pcmsUni", "14.UniqueCleanCluster"))
dimmer <- sapply(pcms, motifStack:::isHomoDimer)
pcms.mono <- lapply(pcms[dimmer], function(.ele){
    pos <- motifStack:::getHomoDimerCenter(.ele)
    .ele$mat <- .ele$mat[, 1:as.numeric(pos["pos"])]
    .ele
})

pcms.mono <- c(pcms[!dimmer], pcms.mono)

unUnique <- unUnique[!sapply(unUnique, function(.ele) .ele$name) %in% names(pcms)]
names(unUnique) <- paste("Dm_cluster", 1:length(unUnique), sep="")
unUnique <- mapply(function(.ele, n) {.ele@name <- n; .ele}, unUnique, names(unUnique))
pfms <- c(lapply(pcms.mono, pcm2pfm), unUnique)
pfms.cp <- c(lapply(pcms, pcm2pfm), unUnique)
pcms <- lapply(pfms, function(.ele){
    mat <- floor(.ele@mat * 1000)
    new("pcm", mat=mat, name=.ele@name)
})

dir.create("uniMotifTmp")
sta <- lapply(pcms, function(.ele){
    mat <- cbind(rownames(.ele@mat), "|", .ele@mat)
    write.table(mat, file=file.path("uniMotifTmp", paste(.ele@name, "pcm", sep=".")), 
                row.names=FALSE, col.names=FALSE, sep="\t", quote=FALSE)
})

uniMotif <- readDataDoAna("uniMotifTmp", groupDistance=NA)
unlink("uniMotifTmp", recursive = TRUE)
attach(uniMotif)
motifs <- pfms.cp[leaves]
motifs=DNAmotifAlignment(motifs, minimalConsensus=3, threshold=.5)
leaveCols <- colorSet[gsub("^(Dm|Mm|Hs)_.*$", "\\1", leaves)]
leaveCols[grepl("cluster", leaves)] <- "gray80"
leaves <- gsub("Dm_cluster", "cluster", leaves)
motifPiles(phylog=phylog, motifs,
           labels.leaves=leaves, col.leaves=leaveCols, col.tree=leaveCols,
           plotIndex=FALSE, clabel.leaves=1.5)

detach(uniMotif)
```