/****************************************************************
 * MatrixAligner (version 4a)					*
 * Copyright (C) 2003, 2004, 2005, 2006                         *
 * Washington University, St. Louis, MO, USA.                   *
 * All Rights Reserved.						*
 * Author:							*
 *  Ting Wang                                                   *
 *  Laboratory of Dr. Gary D. Stormo	                        *
 *  Department of Genetics					*
 *  Washington University in St. Louis				*
 *  Campus Box 8232						*
 *  St. Louis MO 63110						*
 *								*
 *  twang@ural.wustl.edu					*
 ****************************************************************/
 
#include "matalign_options.h"

/* The text of the directions. */
void text_directions(FILE *fp)
{
  fprintf ( fp, "###########################\n" ); 
  fprintf ( fp, "# README FOR MATALIGN-V4a #\n" ); 
  fprintf ( fp, "###########################\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "Copyright 2002--2006 Ting Wang and Gary Stormo\n" ); 
  fprintf ( fp, "May be copied for noncommercial purposes.\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "Author:\n" ); 
  fprintf ( fp, "  Ting Wang and Gary Stormo\n" ); 
  fprintf ( fp, "  Department of Genetics\n" ); 
  fprintf ( fp, "  Washington University in St. Louis\n" ); 
  fprintf ( fp, "  Campus Box 8232\n" ); 
  fprintf ( fp, "  St. Louis, MO 63110\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "  stormo@ural.wustl.edu\n" ); 
  fprintf ( fp, "  twang@ural.wustl.edu\n" ); 
  fprintf ( fp, "  \n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "MatrixAligner-v4a, or \"MegaMatAlign\".\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "NOTES ON THIS UPDATE: \n" ); 
  fprintf ( fp, "MAIN DIFFERENCE FROM V2: batch process of many matrix comparisons.\n" ); 
  fprintf ( fp, "This version allows comparison among many matrices, and fix some bugs.\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "Credit should also be given to Alok Saldanha [alok@caltech.edu] who did\n" ); 
  fprintf ( fp, "lots of initial experimenting with this idea.\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "Strategy: user now provides one or two files that contains file names \n" ); 
  fprintf ( fp, "of matrices to compare. The first line of the file always contains\n" ); 
  fprintf ( fp, "the directory information of the matrices (therefore all matrices should \n" ); 
  fprintf ( fp, "be under the same directory). If one list is provided, all pair-wise\n" ); 
  fprintf ( fp, "comparison will be performed; if two lists are provided, all matrices\n" ); 
  fprintf ( fp, "in list file 1 will be compared to all matrices in list file 2.\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "I also did some software engineering to speed up the comparison.\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "In this version, all matrices should have the format of a count vector.\n" ); 
  fprintf ( fp, "I will allow more variations to the format in later modifications.\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "To illustrate the speed gain, I compared all TRANSFAC matrices against \n" ); 
  fprintf ( fp, "themselves (636 matrices, 201930 comparisons). It took MegaMatAlign about\n" ); 
  fprintf ( fp, "30 seconds to complete the comparison, while if I run a perl script that calls\n" ); 
  fprintf ( fp, "MatAlign that many times, it took almost an hour. So, there is at least \n" ); 
  fprintf ( fp, "a 50~100x gain in speed. \n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "I should also point out that another trick for speeding up the process\n" ); 
  fprintf ( fp, "is to calculate a ALLR lookup table upfront. However, since pseudocount\n" ); 
  fprintf ( fp, "treatment is different between the lookup table and real calculation, \n" ); 
  fprintf ( fp, "the ALLR scores are slightly different. I don't think this will cause \n" ); 
  fprintf ( fp, "significant different, but have to watch out. I may turn this off. Then \n" ); 
  fprintf ( fp, "it would run for twice amount the time, but the logrithm calculation \n" ); 
  fprintf ( fp, "would be more consistent. \n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "#################\n" ); 
  fprintf ( fp, "# BASIC OPTIONS #\n" ); 
  fprintf ( fp, "#################\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "Usage: ./matalign-v4a\n" ); 
  fprintf ( fp, "Use the \"-h\" option for detailed directions\n" ); 
  fprintf ( fp, "-f1 <Name of matrix list file 1>\n" ); 
  fprintf ( fp, "[-h <Print directions>]\n" ); 
  fprintf ( fp, "[-f2 <Name of matrix list file 2>]\n" ); 
  fprintf ( fp, "[-c0 <Compare only the forward orientation>]\n" ); 
  fprintf ( fp, "[-c1 <Compare both orientations (default)>]\n" ); 
  fprintf ( fp, "[-g <Global alignment, (default: 0, for local alignment)>]\n" ); 
  fprintf ( fp, "[-ez <For simple output (only ALLR and Overlap)>]\n" ); 
  fprintf ( fp, "[-a <Name of ascii alphabet file>]\n" ); 
  fprintf ( fp, "[-i <Name of integer alphabet file>]\n" ); 
  fprintf ( fp, "[-A <Ascii alphabet information on the command line>]\n" ); 
  fprintf ( fp, "[-CS <Ascii alphabet is case sensitive (default: ascii alphabets are case insensitive)>]\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "#######################\n" ); 
  fprintf ( fp, "# GENERAL INFORMATION #\n" ); 
  fprintf ( fp, "#######################\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "Matrix Aligner is a program to compare two positional specific matrices.\n" ); 
  fprintf ( fp, "The precursor of this program is \"CompareTwo\". Matalign-v4a made several \n" ); 
  fprintf ( fp, "improvements over the previous establishment of the program.\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "\"MegaMatAlign\" enables comparison of many matrices. The input file contains \n" ); 
  fprintf ( fp, "matrix names (and their location, i.e. directory information). If there is\n" ); 
  fprintf ( fp, "one input list file, MegaMatAlign pair-wise compares all matrices listed\n" ); 
  fprintf ( fp, "in this file; if there are two input list files, then MegaMatAlign compares\n" ); 
  fprintf ( fp, "every matrix listed in file 1 to every matrix listed in file 2.\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "Input PSSMs should be formatted according to consensus output. They \n" ); 
  fprintf ( fp, "should be count matrix like this:\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "(bifrost)[11:06am]src_v4a 574>>more matrix1\n" ); 
  fprintf ( fp, "A |   1   0   0   0   0   0   0\n" ); 
  fprintf ( fp, "C |   0  14   2   0   0   0   9\n" ); 
  fprintf ( fp, "G |  15   2  14  16  16  16   2\n" ); 
  fprintf ( fp, "T |   0   0   0   0   0   0   5\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "The scoring function between two positions of the two matrices is ALLR\n" ); 
  fprintf ( fp, "statistic. The alignment algorithm can be either \"local alignment\" or \n" ); 
  fprintf ( fp, "\"global alignment\". Both options do not allow gaps.\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "The program generates a data table as output. The table contains the\n" ); 
  fprintf ( fp, "following columns, tab-delimited:\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "Matrix_1:      Name of the first matrix in comparison\n" ); 
  fprintf ( fp, "Consensus:     Consensus pattern of the first matrix\n" ); 
  fprintf ( fp, "Matrix_2:      Name of the second matrix in comparison\n" ); 
  fprintf ( fp, "Consensus:     Consensus pattern of the second matrix\n" ); 
  fprintf ( fp, "ALLR:          ALLR score of the comparison. In general, the higher \n" ); 
  fprintf ( fp, "                   the ALLR score, the more similar are the two matrices.\n" ); 
  fprintf ( fp, "Overlap:       The overlap length (bp) of the aligned part\n" ); 
  fprintf ( fp, "Distance:      A distance score. Distance between A and B is defined as:\n" ); 
  fprintf ( fp, "                   ALLR(A,A) + ALLR(B,B) - 2xALLR(A,B).\n" ); 
  fprintf ( fp, "                   In general, the smaller the distance, the more similar \n" ); 
  fprintf ( fp, "                   are the two matrices.\n" ); 
  fprintf ( fp, "Aligned_Dist:  Similar defined as Distance, but only calculated for the \n" ); 
  fprintf ( fp, "                   aligned part.\n" ); 
  fprintf ( fp, "Shared_Consensus:   The aligned part of the two matrices are merged, and a\n" ); 
  fprintf ( fp, "                   new matrix generated. This is the consensus of the \n" ); 
  fprintf ( fp, "                   new matrix.\n" ); 
  fprintf ( fp, "E_value:\n" ); 
  fprintf ( fp, "P_value:       P-value and E-value of the observed ALLR score. These \n" ); 
  fprintf ( fp, "                   significance values are calculated based on \n" ); 
  fprintf ( fp, "                   Karlin-Altschul statistics. The meaning of the p-value \n" ); 
  fprintf ( fp, "                   is, given two random PSSMs, the probability of observing \n" ); 
  fprintf ( fp, "                   an equal or higher ALLR score.      \n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "If \"-ez\" is defined at command line, the output table will only contain \n" ); 
  fprintf ( fp, "Matrix_1, Matrix_2, ALLR, and Overlap for simplicity.\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "########################\n" ); 
  fprintf ( fp, "# COMMAND LINE OPTIONS #\n" ); 
  fprintf ( fp, "########################\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, " 0) -h: print these directions.\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, " 1) Required options\n" ); 
  fprintf ( fp, "    -f1 filename\n" ); 
  fprintf ( fp, "        \"filename\" contains information about matrices: the first line \n" ); 
  fprintf ( fp, "        of the file contains directory, after which every line contains\n" ); 
  fprintf ( fp, "        a matrix file name.\n" ); 
  fprintf ( fp, "    \n" ); 
  fprintf ( fp, "    -f2 filename\n" ); 
  fprintf ( fp, "       \"filename\" contains the second list of matrices.\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, " 2) Alphabet options\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "    -a filename: file containing the alphabet and normalization \n" ); 
  fprintf ( fp, "       information.\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "       Each line contains a letter (a symbol in the alphabet) followed \n" ); 
  fprintf ( fp, "       by an optional normalization number (default: 1.0).  The \n" ); 
  fprintf ( fp, "       normalization is based on the relative prior probabilities of \n" ); 
  fprintf ( fp, "       the letters.  For nucleic acids, this might be be the genomic \n" ); 
  fprintf ( fp, "       frequency of the bases; however, if the \"-d\" option is not used, \n" ); 
  fprintf ( fp, "       the frequencies observed in your own sequence data are used.  \n" ); 
  fprintf ( fp, "       In nucleic acid alphabets, a letter and its complement appear \n" ); 
  fprintf ( fp, "       on the same line, separated by a colon (a letter can be its own \n" ); 
  fprintf ( fp, "       complement, e.g. when using a dimer alphabet). Complementary \n" ); 
  fprintf ( fp, "       letters may use the same normalization number.  Only the standard \n" ); 
  fprintf ( fp, "       26 letters are permissible; however, when the \"-CS\" option is\n" ); 
  fprintf ( fp, "       used, the alphabet is case sensitive so that a total of 52 \n" ); 
  fprintf ( fp, "       different characters are possible.\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "       POSSIBLE LINE FORMATS WITHOUT COMPLEMENTARY LETTERS:\n" ); 
  fprintf ( fp, "       letter\n" ); 
  fprintf ( fp, "       letter normalization\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "       POSSIBLE LINE FORMATS WITH COMPLEMENTARY LETTERS:\n" ); 
  fprintf ( fp, "       letter:complement\n" ); 
  fprintf ( fp, "       letter:complement normalization\n" ); 
  fprintf ( fp, "       letter:complement normalization:complement's_normalization\n" ); 
  fprintf ( fp, "       \n" ); 
  fprintf ( fp, "       Example alphabet file 1:\n" ); 
  fprintf ( fp, "           A:T\n" ); 
  fprintf ( fp, "           C:G\n" ); 
  fprintf ( fp, "       Example alphabet file 2:\n" ); 
  fprintf ( fp, "           A:T 0.3\n" ); 
  fprintf ( fp, "           C:G 0.2\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, " 3) Options for handling the complement of the matrices ---\n" ); 
  fprintf ( fp, "    -c0: ignore the complement \n" ); 
  fprintf ( fp, "    -c1: compare both orientation (the default option)\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, " 4) Algorithm options\n" ); 
  fprintf ( fp, "    \n" ); 
  fprintf ( fp, "    -g: global alignment. Default is local alignment.\n" ); 
  fprintf ( fp, "    -ez: only generate ALLR score and Overlap for each comparison.\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "###########\n" ); 
  fprintf ( fp, "# Example #\n" ); 
  fprintf ( fp, "###########\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "(bifrost)[11:32am]src_v4a 598>>more sample_list \n" ); 
  fprintf ( fp, "/home3/twang/CompareTwo/src_v4a/sample\n" ); 
  fprintf ( fp, "GCN4_01.matrix\n" ); 
  fprintf ( fp, "GCN4_C.matrix\n" ); 
  fprintf ( fp, "HSF_01.matrix\n" ); 
  fprintf ( fp, "HSF_02.matrix\n" ); 
  fprintf ( fp, "HSF_03.matrix\n" ); 
  fprintf ( fp, "HSF_04.matrix\n" ); 
  fprintf ( fp, "HSF_05.matrix\n" ); 
  fprintf ( fp, "(bifrost)[11:32am]src_v4a 599>>more /home3/twang/CompareTwo/src_v4a/sample/GCN4_01.matrix \n" ); 
  fprintf ( fp, "A |   4   2   7   2   3   5   5   4   6  19   0   0  43   0   2   1  43   1  12   4  12   6   7   4   5   8   6\n" ); 
  fprintf ( fp, "C |   6   7   6   7   6   4  11  12   9   6   0   0   0  43   0  42   0  11  16  14  10   9  10   8  10   7   7\n" ); 
  fprintf ( fp, "G |   2   5   2   9   6  10   7   9  11  15   0  43   0   0   0   0   0   5   2  13   4  11   4  11   6   3   4\n" ); 
  fprintf ( fp, "T |   2   1   3   2   8   6   4   5  11   2  43   0   0   0  41   0   0  26   8   3   8   7  10   5   6   7   6\n" ); 
  fprintf ( fp, "(bifrost)[11:33am]src_v4a 600>>more /home3/twang/CompareTwo/src_v4a/sample/GCN4_C.matrix \n" ); 
  fprintf ( fp, "A |  13  25  21   0   0  38   0   0   0   3\n" ); 
  fprintf ( fp, "C |  12   0   0   0   0   0  30   0  38   1\n" ); 
  fprintf ( fp, "G |   8  12  12   0  38   0   0   0   0   0\n" ); 
  fprintf ( fp, "T |   4   0   4  38   0   0   8  38   0   1\n" ); 
  fprintf ( fp, "(bifrost)[11:33am]src_v4a 601>>./matalign-v4a -f1 sample_list -a ~/alphabet -g\n" ); 
  fprintf ( fp, "COMMAND LINE: ./matalign-v4a -f1 sample_list -a /home3/twang/alphabet -g\n" ); 
  fprintf ( fp, " \n" ); 
  fprintf ( fp, "***** PID: 19688 *****\n" ); 
  fprintf ( fp, "Pair-wise comparison among matrices specified in sample_list.\n" ); 
  fprintf ( fp, "Algorithm options:\n" ); 
  fprintf ( fp, "  Compare both orientations.\n" ); 
  fprintf ( fp, "  Global alignment.\n" ); 
  fprintf ( fp, "Output option:\n" ); 
  fprintf ( fp, "  Complete output, including all statistics.\n" ); 
  fprintf ( fp, "Number of pair-wise comparisons: 21\n" ); 
  fprintf ( fp, "Matrix_1        Consensus       Matrix_2        Consensus       ALLR    Overlap Distance        Aligned_Dist    Shared_Consensus        E_value P_value\n" ); 
  fprintf ( fp, "GCN4_01.matrix  nnnnnnnnnRTGACTCAtnSnnnnnnn     GCN4_C.matrix   naaTGACTCa      9.362   10      8.874   7.115   nnaTGACTCA      2.165e-07       2.165e-07\n" ); 
  fprintf ( fp, "GCN4_01.matrix  nnnnnnnnnRTGACTCAtnSnnnnnnn     HSF_01.matrix   aGAAn   -0.018  1       20.037  0.138   n       36.51   1\n" ); 
  fprintf ( fp, "GCN4_01.matrix  nnnnnnnnnRTGACTCAtnSnnnnnnn     HSF_02.matrix   aGAAnaGAAnaGAAn -0.018  1       29.985  0.138   n       109.5   1\n" ); 
  fprintf ( fp, "GCN4_01.matrix  nnnnnnnnnRTGACTCAtnSnnnnnnn     HSF_03.matrix   aGAAnaGAAnnTTCt -0.215  1       30.379  0.743   n       165.4   1\n" ); 
  fprintf ( fp, "GCN4_01.matrix  nnnnnnnnnRTGACTCAtnSnnnnnnn     HSF_04.matrix   aGAAnnTTCtaGAAn -0.018  1       29.985  0.138   n       109.5   1\n" ); 
  fprintf ( fp, "GCN4_01.matrix  nnnnnnnnnRTGACTCAtnSnnnnnnn     HSF_05.matrix   nTTCtaGAAnaGAAn -0.018  1       29.985  0.138   n       109.5   1\n" ); 
  fprintf ( fp, "GCN4_C.matrix   naaTGACTCa      HSF_01.matrix   aGAAn   -0.044  1       17.633  0.210   n       14.3    1\n" ); 
  fprintf ( fp, "GCN4_C.matrix   naaTGACTCa      HSF_02.matrix   aGAAnaGAAnaGAAn -0.044  1       27.581  0.210   n       42.89   1\n" ); 
  fprintf ( fp, "GCN4_C.matrix   naaTGACTCa      HSF_03.matrix   aGAAnaGAAnnTTCt -0.225  1       27.943  1.079   a       62.66   1\n" ); 
  fprintf ( fp, "GCN4_C.matrix   naaTGACTCa      HSF_04.matrix   aGAAnnTTCtaGAAn -0.044  1       27.581  0.210   n       42.89   1\n" ); 
  fprintf ( fp, "GCN4_C.matrix   naaTGACTCa      HSF_05.matrix   nTTCtaGAAnaGAAn -0.044  1       27.581  0.210   n       42.89   1\n" ); 
  fprintf ( fp, "HSF_01.matrix   aGAAn   HSF_02.matrix   aGAAnaGAAnaGAAn 4.974   5       9.948   -0.000  aGAAn   0.000587        0.0005868\n" ); 
  fprintf ( fp, "HSF_01.matrix   aGAAn   HSF_03.matrix   aGAAnaGAAnnTTCt 4.974   5       9.948   -0.000  aGAAn   0.000587        0.0005868\n" ); 
  fprintf ( fp, "HSF_01.matrix   aGAAn   HSF_04.matrix   aGAAnnTTCtaGAAn 4.974   5       9.948   -0.000  aGAAn   0.000587        0.0005868\n" ); 
  fprintf ( fp, "HSF_01.matrix   aGAAn   HSF_05.matrix   nTTCtaGAAnaGAAn 4.974   5       9.948   -0.000  aGAAn   0.000587        0.0005868\n" ); 
  fprintf ( fp, "HSF_02.matrix   aGAAnaGAAnaGAAn HSF_03.matrix   aGAAnaGAAnnTTCt 9.948   10      9.948   -0.000  aGAAnaGAAn      5.288e-08       5.288e-08\n" ); 
  fprintf ( fp, "HSF_02.matrix   aGAAnaGAAnaGAAn HSF_04.matrix   aGAAnnTTCtaGAAn 4.974   5       19.896  -0.000  aGAAn   0.001761        0.001759\n" ); 
  fprintf ( fp, "HSF_02.matrix   aGAAnaGAAnaGAAn HSF_05.matrix   nTTCtaGAAnaGAAn 9.948   10      9.948   -0.000  aGAAnaGAAn      5.288e-08       5.288e-08\n" ); 
  fprintf ( fp, "HSF_03.matrix   aGAAnaGAAnnTTCt HSF_04.matrix   aGAAnnTTCtaGAAn 9.948   10      9.948   -0.000  aGAAnnTTCt      5.288e-08       5.288e-08\n" ); 
  fprintf ( fp, "HSF_03.matrix   aGAAnaGAAnnTTCt HSF_05.matrix   nTTCtaGAAnaGAAn 9.948   10      9.948   -0.000  aGAAnaGAAn      5.288e-08       5.288e-08\n" ); 
  fprintf ( fp, "HSF_04.matrix   aGAAnnTTCtaGAAn HSF_05.matrix   nTTCtaGAAnaGAAn 9.948   10      9.948   -0.000  nTTCtaGAAn      5.288e-08       5.288e-08\n" ); 
  fprintf ( fp, "(bifrost)[11:33am]src_v4a 603>>./matalign-v4a -f1 sample_list -f2 sample_list -a ~/alphabet -g -ez\n" ); 
  fprintf ( fp, "COMMAND LINE: ./matalign-v4a -f1 sample_list -f2 sample_list -a /home3/twang/alphabet -g -ez\n" ); 
  fprintf ( fp, " \n" ); 
  fprintf ( fp, "***** PID: 32161 *****\n" ); 
  fprintf ( fp, "Compare all matrices specified in sample_list to all matrices specified in sample_list.\n" ); 
  fprintf ( fp, "Algorithm options:\n" ); 
  fprintf ( fp, "  Compare both orientations.\n" ); 
  fprintf ( fp, "  Global alignment.\n" ); 
  fprintf ( fp, "Output option:\n" ); 
  fprintf ( fp, "  Simple output, only names of matrices, ALLR and Overlap.\n" ); 
  fprintf ( fp, "Number of pair-wise comparisons: 49\n" ); 
  fprintf ( fp, "Matrix_1        Matrix_2        ALLR    Overlap\n" ); 
  fprintf ( fp, "GCN4_01.matrix  GCN4_01.matrix  15.027  27\n" ); 
  fprintf ( fp, "GCN4_01.matrix  GCN4_C.matrix   9.362   10\n" ); 
  fprintf ( fp, "GCN4_01.matrix  HSF_01.matrix   -0.018  1\n" ); 
  fprintf ( fp, "GCN4_01.matrix  HSF_02.matrix   -0.018  1\n" ); 
  fprintf ( fp, "GCN4_01.matrix  HSF_03.matrix   -0.215  1\n" ); 
  fprintf ( fp, "GCN4_01.matrix  HSF_04.matrix   -0.018  1\n" ); 
  fprintf ( fp, "GCN4_01.matrix  HSF_05.matrix   -0.018  1\n" ); 
  fprintf ( fp, "GCN4_C.matrix   GCN4_01.matrix  9.362   10\n" ); 
  fprintf ( fp, "GCN4_C.matrix   GCN4_C.matrix   12.570  10\n" ); 
  fprintf ( fp, "GCN4_C.matrix   HSF_01.matrix   -0.044  1\n" ); 
  fprintf ( fp, "GCN4_C.matrix   HSF_02.matrix   -0.044  1\n" ); 
  fprintf ( fp, "GCN4_C.matrix   HSF_03.matrix   -0.225  1\n" ); 
  fprintf ( fp, "GCN4_C.matrix   HSF_04.matrix   -0.044  1\n" ); 
  fprintf ( fp, "GCN4_C.matrix   HSF_05.matrix   -0.044  1\n" ); 
  fprintf ( fp, "HSF_01.matrix   GCN4_01.matrix  -0.018  1\n" ); 
  fprintf ( fp, "HSF_01.matrix   GCN4_C.matrix   -0.044  1\n" ); 
  fprintf ( fp, "HSF_01.matrix   HSF_01.matrix   4.974   5\n" ); 
  fprintf ( fp, "HSF_01.matrix   HSF_02.matrix   4.974   5\n" ); 
  fprintf ( fp, "HSF_01.matrix   HSF_03.matrix   4.974   5\n" ); 
  fprintf ( fp, "HSF_01.matrix   HSF_04.matrix   4.974   5\n" ); 
  fprintf ( fp, "HSF_01.matrix   HSF_05.matrix   4.974   5\n" ); 
  fprintf ( fp, "HSF_02.matrix   GCN4_01.matrix  -0.018  1\n" ); 
  fprintf ( fp, "HSF_02.matrix   GCN4_C.matrix   -0.044  1\n" ); 
  fprintf ( fp, "HSF_02.matrix   HSF_01.matrix   4.974   5\n" ); 
  fprintf ( fp, "HSF_02.matrix   HSF_02.matrix   14.922  15\n" ); 
  fprintf ( fp, "HSF_02.matrix   HSF_03.matrix   9.948   10\n" ); 
  fprintf ( fp, "HSF_02.matrix   HSF_04.matrix   4.974   5\n" ); 
  fprintf ( fp, "HSF_02.matrix   HSF_05.matrix   9.948   10\n" ); 
  fprintf ( fp, "HSF_03.matrix   GCN4_01.matrix  -0.215  1\n" ); 
  fprintf ( fp, "HSF_03.matrix   GCN4_C.matrix   -0.225  1\n" ); 
  fprintf ( fp, "HSF_03.matrix   HSF_01.matrix   4.974   5\n" ); 
  fprintf ( fp, "HSF_03.matrix   HSF_02.matrix   9.948   10\n" ); 
  fprintf ( fp, "HSF_03.matrix   HSF_03.matrix   14.922  15\n" ); 
  fprintf ( fp, "HSF_03.matrix   HSF_04.matrix   9.948   10\n" ); 
  fprintf ( fp, "HSF_03.matrix   HSF_05.matrix   9.948   10\n" ); 
  fprintf ( fp, "HSF_04.matrix   GCN4_01.matrix  -0.018  1\n" ); 
  fprintf ( fp, "HSF_04.matrix   GCN4_C.matrix   -0.044  1\n" ); 
  fprintf ( fp, "HSF_04.matrix   HSF_01.matrix   4.974   5\n" ); 
  fprintf ( fp, "HSF_04.matrix   HSF_02.matrix   4.974   5\n" ); 
  fprintf ( fp, "HSF_04.matrix   HSF_03.matrix   9.948   10\n" ); 
  fprintf ( fp, "HSF_04.matrix   HSF_04.matrix   14.922  15\n" ); 
  fprintf ( fp, "HSF_04.matrix   HSF_05.matrix   9.948   10\n" ); 
  fprintf ( fp, "HSF_05.matrix   GCN4_01.matrix  -0.018  1\n" ); 
  fprintf ( fp, "HSF_05.matrix   GCN4_C.matrix   -0.044  1\n" ); 
  fprintf ( fp, "HSF_05.matrix   HSF_01.matrix   4.974   5\n" ); 
  fprintf ( fp, "HSF_05.matrix   HSF_02.matrix   9.948   10\n" ); 
  fprintf ( fp, "HSF_05.matrix   HSF_03.matrix   9.948   10\n" ); 
  fprintf ( fp, "HSF_05.matrix   HSF_04.matrix   9.948   10\n" ); 
  fprintf ( fp, "HSF_05.matrix   HSF_05.matrix   14.922  15\n" ); 
  fprintf ( fp, "(bifrost)[11:34am]src_v4a 604>>\n" ); 
  fprintf ( fp, "\n" ); 
  fprintf ( fp, "\n" ); 


}